[Feat] #32 - Home 구현
Link-MIND/TOASTER-iOS pull request #55
Opened 2024-01-11 13:17 UTC by mcrkgus

## ✨ 해결한 이슈 

- Resolved: #32 

## 🛠️ 작업내용

|    구현 내용    |   SE   |   13 mini   |   15 pro   |
| :-------------: | :----------: | :----------: | :----------: |
| GIF | ![iPhone SE](https://github.com/Link-MIND/TOASTER-iOS/assets/101050833/a7c6238b-70ca-419f-9475-f403431aa432) | ![iPhone 13 mini](https://github.com/Link-MIND/TOASTER-iOS/assets/101050833/d563e1f8-92f7-4d30-a9af-4684a474c510) | ![iPhone 15 Pro](https://github.com/Link-MIND/TOASTER-iOS/assets/101050833/4986e3be-5eb1-4fd3-93dc-61384c7ba8f2) |

## 🖥️ 주요 코드 설명

`CompositionalFactory`
- Compositional Layout을 사용하기 위해 section 별로 layout을 구현했습니다.
```swift
enum CompositionalFactory {
    static func create() -> UICollectionViewCompositionalLayout {
        return UICollectionViewCompositionalLayout { (sectionNumber, _ environment) -> NSCollectionLayoutSection? in
            let section: NSCollectionLayoutSection
            switch sectionNumber {
            case 0:
                section = createMainSection()
            case 1:
                section = createUserClipSection()
            case 2:
                section = createWeeklyLinkSection()
            case 3:
                section = createWeeklyRecommendSection()
            default:
                section = createMainSection()
            }
            return section
        }
    } 
```

`HomeViewController`
- UserClip section에서 cell을 선택할 때마다 BottomSheet가 올라오게 했습니다. 
```swift
func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if indexPath.row == clipCellData.count - 1 {
            addClipCellTapped()
        }
    }
```

`MainCollectionViewCell`
- ProgressView는 API 연동 후에 변경하겠습니다. (readToastNum, allToastNum)
```swift
linkProgressView.do {
            $0.trackTintColor = .gray100
            $0.progressTintColor = .toasterPrimary
            $0.progress = Float(readToastNum)/Float(allToastNum)
            $0.makeRounded(radius: 8)
            $0.clipsToBounds = true
        }
```

`MainInfoModel`, `UserClipEmptyCollectionViewCell`, `WeeklyLinkCollectionViewCell` 
- 서버 통신 이후 수정

## 📂 참고한 내용

## ✅ Checklist
- [ ] 필요없는 주석, 프린트문 제거했는지 확인
- [ ] 컨벤션 지켰는지 확인

2024-01-11 13:44 UTC, Sangwook123 reviewed
잘하시네요

2024-01-11 13:44 UTC, Sangwook123 commented on TOASTER-iOS/Global/Consts/ImageLiterals.swift
> +        static var searchIcon: UIImage { .load(name: "ic_search_20") }
p3 : 
enum 활용 좋습니다 ~

2024-01-11 14:26 UTC, Genesis2010 approved these changes
p3:
정말 고생 많으셨습니다!
완벽한 MainView 가 될거 같아요!

2024-01-11 14:26 UTC, Genesis2010 commented on TOASTER-iOS/Present/Home/View/Cell/WeeklyLinkCollectionViewCell.swift
> +}
p3:
빈칸 삭제해주시면 감사하겠습니다!

2024-01-11 14:59 UTC, yeahh315 approved these changes
p3:
제일 무거운 메인 화면 구현한 천재 개발자가 여기에! 🔥❤️

2024-01-11 14:59 UTC, yeahh315 commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +    }
p2:
컨벤션 따라서 private extension으로 빼주는게 좋을 것 같아요!

2024-01-11 14:59 UTC, yeahh315 commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +        }
p3:
섹션 3의 경우를 default에 넣는 것보다 따로 case로 나눠서 하는게 더 가독성이 좋을 것 같아요!

2024-01-11 14:59 UTC, yeahh315 commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +        }
p3:
이런 부분 할 때 else 처리해서 클립 추가 로직 말고 클립 선택 로직도 구현해두면 나중에 편할 것 같아요!

2024-01-11 14:59 UTC, yeahh315 commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
p3:
이후에 리펙을 진행한다면 색션 1, 2, 3의 헤더는 동일한 HeaderView를 재사용해서 만들어줘도 좋을 것 같아요!

2024-01-11 14:59 UTC, yeahh315 commented on TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
> +    var allToastNum: Int = 47
p2:
접근 제어자를 private으로 지정하고 configure하는 함수를 만들어주는 로직으로 바꾸는 것도 좋을 것 같아요!

2024-01-11 14:59 UTC, yeahh315 commented on TOASTER-iOS/Present/Home/View/CompositioinalFactory.swift
p3:
이후에 리펙 진행할 때 itemSize나 groupSize를 프로퍼티에 담고, 파라미터로 전달받아 NSCollectionLayoutSection을 만드는 함수를 하나로 만들어줘도 좋을 것 같아요!

2024-01-11 14:59 UTC, yeahh315 commented on TOASTER-iOS/Present/Home/View/Footer/MainFooterCollectionView.swift
p2:
하나의 footer를 재사용해도 될 것 같아요!

2024-01-11 15:29 UTC, mini-min requested changes
홈 구현했으니까 TabBarItem에도 바로 연결해주면 좋을 것 같아요~

2024-01-11 15:29 UTC, mini-min commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +        homeCollectionView.register(UserClipEmptyCollectionViewCell.self,forCellWithReuseIdentifier: UserClipEmptyCollectionViewCell.className)
p1:
콤마 띄어주세요

2024-01-11 15:29 UTC, mini-min commented on TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
> +            $0.setTitleColor(.gray400, for: .normal)
p1:
title 폰트가 지정되어있지가 않습니다
regular_16으로 지정해주세요~

2024-01-11 15:29 UTC, mini-min commented on TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
> +        }
p1:
해당 부분 줄간격(행간)을 잡아줘야할거 같아요!
피그마에는 userLabel이랑 noticeLabel 떨어져있는 간격과, 링크를 / 잊지 않고 사이 떨어져있는 간격이 동일하게 되어있습니다~
참고 링크입니다~ https://developer-fury.tistory.com/37

2024-01-11 15:29 UTC, mini-min commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +                cell.configureCell(forModel: CategoryList(categoryId: 0, categroyTitle: "전체클립", toastNum: 100))
p1:
전체클립 고정 아이콘 바뀐거 확인하고 이미지 0번째 cell만 다르게 설정해주세요!
이미지는 저도 클립뷰에서 사용해서 이미 Asset에 있을겁니다~

2024-01-11 15:29 UTC, mini-min commented on TOASTER-iOS/Global/Resources/Assets.xcassets/ic_clip_default_24.imageset/Contents.json
p1:
ic_all_clip_24라는 이름으로 이미 Asset에 있는 이미지와 동일합니다!
이 이미지는 지우고, 사용하는 부분에서 ic_all_clip_24로 바꿔서 사용해주세요~

2024-01-11 15:29 UTC, mini-min commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
p1:
린트에서도 함수의 복잡도를 체크하는 cyclomatic_complexity Warning이 발생중입니다!
headerView 재사용하는 코드로 바꾸면 동시에 이 경고도 없어질 듯 합니다아

2024-01-11 15:29 UTC, mini-min commented on TOASTER-iOS/Present/Home/View/Cell/MainCollectionViewCell.swift
> +            $0.titleEdgeInsets = .init(top: 0, left: 20, bottom: 0, right: 0)
p2:
'imageEdgeInsets' was deprecated in iOS 15.0: This property is ignored when using UIButtonConfiguration가 발생합니다!
DeleteLinkBottomSheetView에 있는 deleteButton.do 부분이 UIButton.Configuration으로 구현되어 있으니 참고해서 변경해주면 좋을 것 같습니다.

2024-01-11 15:59 UTC, mcrkgus commented on TOASTER-iOS/Present/AddLink/View/AddLinkView.swift
> +        }
AddLink는 따로 PR 다시 올리겠습니당!

2024-01-11 16:51 UTC, mcrkgus commented on TOASTER-iOS/Present/AddLink/View/AddLinkView.swift
> +        titleTextField.delegate = self
AddLink는 나중에 따로 PR 올리겠습니당

2024-01-11 16:54 UTC, mcrkgus commented on TOASTER-iOS/Present/Home/HomeViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
재사용이 넘 중요하군요 감사합니다 ㅎㅎ

2024-01-11 17:50 UTC, lsakee approved these changes
LGTM 고생하셨어요

2024-01-11 18:03 UTC, mcrkgus commented on TOASTER-iOS/Global/Consts/ImageLiterals.swift
> +        static var searchIcon: UIImage { .load(name: "ic_search_20") }
감사함다 ㅋㅋ ~

2024-01-12 07:19 UTC, mini-min approved these changes

2024-01-12 07:27 UTC, merged